###############################################################################
# Makefile for the project juice
###############################################################################

## General Flags
PROJECT = juice
TARGET = juice
MCU = atmega168a
CC = avr-gcc

CPP = avr-g++

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU)

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -std=gnu99 -DF_CPU=7372800UL -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=juice.map


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom -R .fuse -R .lock -R .signature

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Objects that must be built in order to link
OBJECTS = twi-server.o servo.o swuart.o rs485.o

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
#all: $(TARGET).elf $(TARGET).hex $(TARGET).lss size
all: $(TARGET).elf $(TARGET).hex

## Compile
twi-server.o: twi-server.c juice.h
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

servo.o: servo.c juice.h
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

swuart.o: swuart.c juice.h
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

rs485.o: rs485.c juice.h
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<


##Link
$(TARGET).elf: $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET).elf

%.hex: $(TARGET).elf
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET).elf
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET).elf
	avr-objdump -h -S $< > $@

size: $(TARGET).elf
	@echo
	@avr-size -C --mcu=${MCU} $(TARGET).elf

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) dep/* $(TARGET).elf $(TARGET).hex $(TARGET).eep $(TARGET).lss $(TARGET).map *~


## Other dependencies
-include $(shell mkdir dep 2>/dev/null) $(wildcard dep/*)

